version: '3.5'

services:
  api:
    container_name: $APP_CONTAINER
    image: symfony
    build:
      context: ./docker
      dockerfile: ./Dockerfile
      args:
        USER: ${USER}
      ## environment:
      ## XDEBUG_CLIENT_HOST: host.docker.internal
      ## XDEBUG_CLIENT_PORT: 9003

    volumes:
      - ./:/var/www/html
    ###> XDEBUG 3 ###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # Windows (with WSL2) and Mac: host.docker.internal

    ports:
      - '${DEVELOPMENT_WEB_PORT}:80'
    networks:
      - untoldwords-network
    depends_on:
      - bbdd

  bbdd:
    container_name: ${APP_CONTAINER}-bbdd
    image: mysql:8.2.0
    restart: always
    ports:
      - "${DEVELOPMENT_DATABASE_PORT}:3306"
    environment:
      MYSQL_DATABASE: "${DEVELOPMENT_DATABASE_NAME}"
      MYSQL_ROOT_PASSWORD: "${DEVELOPMENT_DATABASE_ROOT_PASSWORD}"
      MYSQL_USER: "${DEVELOPMENT_DATABASE_USER}"
      MYSQL_PASSWORD: "${DEVELOPMENT_DATABASE_PASSWORD}"
    volumes:
      - untoldwords-bbdd-data:/var/lib/mysql
    networks:
      - untoldwords-network
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
  # mailer:
  #  image: axllent/mailpit
  #  ports:
  #    - "1025"
  #    - "8025"
  #  environment:
  #    MP_SMTP_AUTH_ACCEPT_ANY: 1
  #    MP_SMTP_AUTH_ALLOW_INSECURE: 1

networks:
  untoldwords-network:


volumes:
  untoldwords-bbdd-data:
